---
title: "Why Philip K. Dick?"
author: "Yann Audin"
date: "2025-09-01"
categories: ["Philip K. Dick Project", "Literature"]
tags: ["Philip K. Dick"]
bibliography: references.bib
format:
  html:
    toc: true
    number-sections: true
    code-fold: true
description: "On my own connection to Philip K. Dick and why he matters today"
draft: true # Set to false when ready to publish
---

::: {.callout-important icon="false"}

## **If nothing I say could convince you to read science-fiction:**

I am well aware that if you think that S-F cannot hold literary value, it's unlikely that I could convince you to read Philip K. Dick if I were to describe it as "science-fiction, but even weirder". Instead, here is my half-baked appeal to canonicity on why you might want to try to read some S-F and Dick's work:

- In most "best books of all time" lists, science-fiction tends to take 4--5% of the spots[^lists] despite being a relatively young and marginal genre;
- Philip K. Dick was the first science-fiction author to be included in *The Library of America* series;
- More than 26 000 scholarly articles mention him and his work inspired Jean Baudrillard's *Simulacres et simulation*[^baudrillard];
- Dick's extensive body of work is still being adapted to television and cinema (sometimes directly, often indirectly), and he has had a lasting impact on multiple genre beyond science-fiction and speculative fiction.

However if the tropes of science-fiction are enough to make you put down a book, I don't actually believe that you actually *should* read Philip K. Dick. That being said...

:::

## Why I think you should read some Philip K. Dick

To know Philip K. Dick's work is to recognize him everywhere. When the nature of reality is contested in contemporary media, one can usually draw a line to Dick, either directly -- *Bladerunner*, *The Adjustment Bureau*, *Total Recall*, *Philip K. Dick's Electric Dreams*, *Minority Report*, ... -- or indirectly -- *The Matrix*, *Donnie Darko*, *Eternal Sunshine of the Spotless Mind*, *The Truman Show*, *Westworld*, ... 

Dick was wrapped into the culture of his time: he did not set himself apart from society as an observer, nor was he a literary recluse, opting for a social and socially engaged life. 

This is not to say that Philip K. Dick changed much of the culture around him. In many ways, he was more wrapped by and subjucated to the pressures of his time than many other authors who set themselves outside of society as observers, and he did not become a literary recluse, opting for a socially active and engaged life. Dick was first and foremost an American white man who grew up and lived in an era of extraordinary and frightening technological and cultural transformations, and who became a creative nexus for the formidable and overwhelming forces of his time. 

The pressures of the World Wars and the Cold Wars, the blooming of psychology, the rediscovery of ancient Christian texts, post-war interests in psychoanalysis and esoterism, California's drug culture, military experiemnts with LSD, the rise of no-fault divorce in the US, the boom of pulp sci-fi, the blind enthousiasm of futurism, the post-truth mediatic turn, quantum mechanics and cosmology, the space race, the first serious talks of artificial intelligence and androids, the Bomb and its aftermath... Philip K. Dick lived and captured all of it and more. He transformed the falseness and the brokeness of a life that is both extremely specific -- being an American in the 50s, 60s and 70s -- and completely generalisable -- living with crushing doubt and through sweeping changes -- into literary truth, published in the silliest of genre: science-fiction.

That being said, one must also make a case to study Philip K. Dick's letters and non-fiction :

> But the state of things is so dreary here in the U.S.— they say the elderly and poor are eating canned dogfood, now, to stay alive, and the McDonald hamburg­ers are made from cows’ eyes. The radio also says that today when Charles Colson, the President’s former counsel, went into jail he still wore his Richard M. Nixon tieclasp. “California dreaming is becoming a reality,” is a line from a Mamas & The Papas song of a few years ago, but what a dreadful surreal reality it is: foglike and dangerous, with the subtle and terrible manifestations of evil rising up like rocks in the gloom. I wish I was somewhere else. Disneyland, maybe. The last sane place here? Forever to take Mr. Toad’s Wild Ride and never get off? [@dick_letters3_1974]

## The Dickian question

The question at the core of [Philip K. Dick](pkd_01.qmd)'s project is the same one that lead me to study physics at the graduate level, and the same one that still animates me in my literary studies to this day: "What is reality?"

> Reality is that which, when you stop believing in it, doesn't go away.
> -- Philip K. Dick, *I Hope I Shall Arrive Soon* [-@dick_hope_TODO]

Reality isn't something that is easy to understand; it seems that any one approach to try to grasp at it is a form of epistemic violence towards the universe itself, and a combination of approach inevariably leads to the need for incompatible points of view to exist simultaneously. Paul Valéry wrote "Nous ne raisonnons que par modèles" ["We only think through models", my translation], but systems are never complete, they do not hold to scrutiny like we hope something like a universe should/would. What if the (human) universe is, like language and mathematics, a system created by the network of affordances and perceptual horizons humans inherited from the laws of physics, language and culture? 

How does one take hold of the system of which they are a part of? This reformulation of the question can be applied to mathematics, physics and language alike: the pretension of objectivity fails systematically, is the unobserved universe worth creating? 

Studying the universe might lead to the same dead ends described by Gödel in his Incompleteness theorems: mathematical systems cannot justify themselves. According to the first incompletness theorem, there is no consistent set of axioms for mathematics that allows one to prove all truths about arithmetics. Even worse, the second incompletness theorem proves that no system can prove its own self-consistency. Beyond formal systems, Münchhausen's trilemna make a similar case for knowledge

Fries' Trilemna tries to address this limit by reframing the problem: things can be known dogmatically, through infinite regresses, or by basing oneself on perceptual experience. This answer seems to point to empiricism as a simple solution to the problem of epistemology, but perceptual experience is not something you can systematically trust, and for someone like Philip K. Dick who lived between multiple realities, perception can't be the answer: if most people cannot see the cage in which they stand, and the few that know t


Frank Herbert also touches on the Dickian question, although he comes at it from a spiritual (and less neurotic) avenue:

> She said the mystery of life isn’t a problem to solve, but a reality to experience. So I quoted the First Law of Mentat at her: "A process cannot be understood by stopping it. Understanding must move with the flow of the process, must join it and flow with it."
> -- Frank Herbert, *Dune* [-@herbert_dune_1965]

Dick does not see the mystery of life as a flow in which one can let themselves go, he knows enough to know the shape of the prison, and presents his view of breaking out in *Valis*:

> To fight the Empire is to be infected by its derangement ... Whoever defeats the Empire becomes the Empire; it proliferates like a virus ... thereby it becomes its enemies. 
> -- Philip K. Dick, *Valis* [-@dick_valis_TODO]

### No one is prophet in their own (time or) country

My views on Philip K. Dick are tainted by regret: on one hand, if he had been born at any other time or place, he might have been taken seriously; he might have been the philosopher that his time needed as well as the one our time needs. On the other hand, if he had been born at any other time or place, he wouldn't be Philip K. Dick. His work was confined to science-fiction by material and cultural forces beyond his control -- he only manage to have one of his non-scifi novel published -- keeping his idea in stasis, away from serious criticism. 

> The fact that what Dick is entertaining us about is reality and madness,time and death, sin and salvation -- this has escaped most readers and critics. Nobody notices; nobody notices that we have our own homegrown Borges, and have had him for 30 years
> -- Ursula K. Leguin, "Science Fiction as Prophesy" [-@leguin_science_1976]^[The original article from *The New Repulbic* vol. 175 is not readily available online, so this quote was retrieved from "Edmundo Paz Soldán and his Precursors: Borges, Dick, and the SF Canon" [@soldan_edmundo_2007]. ]

As for any other speculative fiction writer, some of Philip K. Dick's prediction came to pass, others are well on their way, and others are still the subject of more science-fiction than actual science. His insight on communication technologies and the consequences of handing so much information and power to a small number of telecommunication corporations [@dick_TODO] seems evident to the modern audience. In *Do Androids Dream of Electric Sheep*, his description of *Buster Friendly and his Friendly Friends* -- a 24/7 news and variety show starring a never aging, never tiring cast that is later revealed to be fully automated -- warns us of parasocial relationships, infinite scrolling, deepfakes and AI generated content. 

## Why do I study Philip K. Dick

Part of it is simply that I grew up reading his stories and still do enjoy them, although that is not enought to warrant a research blog^[That being said, research subjects are often the result of personal feelings in literature: we do not spend hundreds of hours working on a subject that we don't like just for the sake of "producing" articles and books, or at least I hope not.].
Another part of it is my fascination with the literary character that is Philip K. Dick and the improbable life he lead as well as the impact he still has on us to this day. 
But then again, that does not explain why I should write about him today, because the real reason is deeper and, I am afraid, more sinister. 
Like Albert Camus, Margaret Atwood, Samuel Beckett, and other literary philosophers, Philip K. Dick doesn't simply write.
He is not bound by aesthetic or storytelling, is main thesis is not political^[Although it should be remembered that he wrote extensively on the Cold War, the threat nuclear war, authoritarianism, communism, late stage capitalism and fascism.], nor is it aspirational.
No, Philip K. Dick has a philosophy about the nature of reality that encompasses many of the troubles, both social and political, of our current age.

> So I ask, in my writing, What is real? Because unceasingly we are bombarded with pseudorealities manufactured by very sophisticated people using very sophisticated electronic mechanisms. I do not distrust their motives; I distrust their power. They have a lot of it. And it is an astonishing power: that of creating whole universes, universes of the mind. I ought to know. I do the same thing. 
> 
> Philip K. Dick, How To Build A Universe That Doesn't Fall Apart Two Days Later (1978)

Moreover, the genre of science-fiction allowed him to adress issues that did not even exist during his time that are not central to our current era. 

The fact that PKD presented his work as a reflexion on the nature of reality and mankind warrants greater academic attention, which this blog will hopefully contribute to^[On that matter, I blame the bias against science-fiction: the *serious* literary scene does not discuss it and reduces it to laser guns and aliens. (Do not take me wrong, I like laser guns and aliens as much as the next 30 years old man who's first memory of going to the cinema is seeing *Star Wars: The Phantom Menace* with their dad.) If I don't think that an apology of science-fiction is necessary, I might put in word my **strong** feelings on the matter in the future.]. 
But the main and central reason why I personally decided to write about Philip K. Dick is that I was, long ago, infected by his ideas. 

> Is there anyone there\
> Who understands me?\
> Anyone at all?\
> [...]\
> I have to know what is real\
> And what is illusion\
> Oh, how does it feel\
> Beyond this confusion?\
> 
> -- "Monkeyland", The Chameleons UK (1983)

## Bibliography

:::{.refs}

:::

[^lists]: Estimate based on a quick, informal research, please do not cite this number. I consulted the [Time Magazine](https://www.goodreads.com/list/show/2681.Time_Magazine_s_All_Time_100_Novels), [*Le Monde*'s 100 Books of the Century](https://en.wikipedia.org/wiki/Le_Monde%27s_100_Books_of_the_Century), [The Greatest Books' Global Literary Canon](https://thegreatestbooks.org/global-canon), [the Modern Library's 100 Best Novels](https://sites.prh.com/modern-library-top-100/#top-100-novels), [PBS's The Great American Read](https://www.pbs.org/the-great-american-read/books/#/), [Pinguin and Random House's 100 must-read classics](https://www.penguin.co.uk/discover/articles/100-must-read-classic-books), and [The Guardian's "The best novels written in English](https://www.theguardian.com/books/2015/aug/17/the-100-best-novels-written-in-english-the-full-list). Dystopias dominate these lists with Orwell's *1984*, Burgess' *A Clockwork Orange* and Huxley's *Brave New World*. Philip K. Dick's *Ubik* makes a few appearances. 

[^baudrillard]: Although the strength of this connection is challenged by Jorge Martins Rosa in his 2008 articles "A Misreading Gone Too Far? Baudrillard Meets Philip K. Dick": it seems like Baudrillard made a series of mistake in his reading of Dick's novels, confusing and conflating plots, ignoring fundamental aspects of Dick's word---such as the phantom twin, see ["Who is Philip K. Dick?"](pkd_01.qmd), and even mispelling Dick's name multiple times [@rosa_misreading_2008]. 