---
title: "About The Author"
author: "Yann Audin"
date: "2025-03-21"
format:
  html:
    toc: true
    toc-depth: 2
---

I am a PhD candidate at the University of Montreal and my research interests are Digital Humanities, Literature and Epistemology. I am affiliated, through my supervisors Marcello Vitali-Rosati and Dominic Forest, to the [Centre de recherche interuniversitaire sur les humanités numériques](crihn.org), and to the [Canadian Society for Digital Humanities](https://csdh-schn.org/) as a graduate representative. 

## Recent publications

- [For a General Theory of Scholars–Digital Tools Interactions](https://www.digitalstudies.org/article/id/11058/)
- [Notes sur le projet « Digital Leigh Hunt »](https://hal.science/hal-04227199/document)

## Proceedings

- [Des algorithmes pour définir des concepts littéraires?](https://hal.science/hal-04563545/document)
- [Le projet Intelligence artificielle littéraire (IAL): définir formellement le concept de variation au sein de l'Anthologie grecque?](https://umontreal.scholaris.ca/server/api/core/bitstreams/e6488a67-2524-4b17-93e0-97a45c56f746/content)
- [Intelligence Artificielle Littéraire](https://hal.science/hal-04131573v1/file/Humanistica_2023_audin.pdf)
- [The Importance of Single Source Publishing in Scientific Publishing](https://hal.science/hal-04333303/document)
