---
title: "Why do I study Philip K. Dick?"
author: "Yann Audin"
date: "2025-12-06"
categories: ["Philip K. Dick Project", "Literature"]
tags: ["Philip K. Dick"]
bibliography: references.bib
format:
  html:
    toc: true
    number-sections: true
    code-fold: true
description: "On my own connection to Philip K. Dick and why he matters to me."
draft: true # Set to false when ready to publish
---


> Is there anyone there\
> Who understands me?\
> Anyone at all?\
> [...]\
> I have to know what is real\
> And what is illusion\
> Oh, how does it feel\
> Beyond this confusion?\
> 
> -- "Monkeyland", The Chameleons UK (1983)

## Why do I study Philip K. Dick

Part of it is simply that I grew up reading his stories and still do enjoy them, although that is not enought to warrant a research blog^[That being said, research subjects are often the result of personal feelings in literature: we do not spend hundreds of hours working on a subject that we don't like just for the sake of "producing" articles and books, or at least I hope not.].
Another part of it is my fascination with the literary character that is Philip K. Dick and the improbable life he lead as well as the impact he still has on us to this day. 
But then again, that does not explain why I should write about him today, because the real reason is deeper and, I am afraid, more sinister. 
Like Albert Camus, Margaret Atwood, Samuel Beckett, and other literary philosophers, Philip K. Dick doesn't simply write.
He is not bound by aesthetic or storytelling, is main thesis is not political^[Although it should be remembered that he wrote extensively on the Cold War, the threat nuclear war, authoritarianism, communism, late stage capitalism and fascism.], nor is it aspirational.
No, Philip K. Dick has a philosophy about the nature of reality that encompasses many of the troubles, both social and political, of our current age.

> So I ask, in my writing, What is real? Because unceasingly we are bombarded with pseudorealities manufactured by very sophisticated people using very sophisticated electronic mechanisms. I do not distrust their motives; I distrust their power. They have a lot of it. And it is an astonishing power: that of creating whole universes, universes of the mind. I ought to know. I do the same thing. 
> 
> Philip K. Dick, How To Build A Universe That Doesn't Fall Apart Two Days Later (1978)

Moreover, the genre of science-fiction allowed him to adress issues that did not even exist during his time that are not central to our current era. 

The fact that PKD presented his work as a reflexion on the nature of reality and mankind warrants greater academic attention, which this blog will hopefully contribute to^[On that matter, I blame the bias against science-fiction: the *serious* literary scene does not discuss it and reduces it to laser guns and aliens. (Do not take me wrong, I like laser guns and aliens as much as the next 30 years old man who's first memory of going to the cinema is seeing *Star Wars: The Phantom Menace* with their dad.) If I don't think that an apology of science-fiction is necessary, I might put in word my **strong** feelings on the matter in the future.]. 
But the main and central reason why I personally decided to write about Philip K. Dick is that I was, long ago, infected by his ideas. 

> I got a letter from a fellow science fiction writer who had reviewed VALIS, favorably... he mentioned that he had himself done a novel based on Gnosticism, and I wrote him raising several issues basic to Gnosticism, whereupon he wrote back to say that he considered such matters essentially "futile game," and, what was more, dangerous to play around with. "I have a family to support," he wrote. "I don't dare think about such things" (I'm paraphrasing, but that is the gist of it). What a dreadful thing: that someone would consider ideas too dangerous to think about, [he] even went so far to suggest that it was very possible that you could become crazy due to wondering about fundamental epistemological, philosophical questions. Good lord; have we come to that?
> 
>  An intellectual dark age seems to be settling over the United States. People are literally frightened by new ideas. [...] I suppose there is a risk. There has *always* been a risk. But is not this risk a grand risk, the sign of a noble heart? The intellectual pioneers of our species ventured forth in the contemplation and analysis of "dangerous" ideasl; this is how we have come to acquire a vast heritage of knowledge and wisdom. And yet---people are afraid. The question I put to this writer is, "Does the universe in fact exist, or are we compelled by some mysterious agency to take it ineluctably for real? That is, we are compelled against our choice---even our knowledge---to take it to be real." [@dick_selected1981-1982]

## No one is prophet in their own (time or) country

My views on Philip K. Dick are tainted by regret: on one hand, if he had been born at any other time or place, he might have been taken seriously; he might have been the philosopher that his time needed as well as the one our time needs. On the other hand, if he had been born at any other time or place, he wouldn't be Philip K. Dick. His work was confined to science-fiction by material and cultural forces beyond his control -- he only manage to have one of his non-scifi novel published -- keeping his idea in stasis, away from serious criticism. 

> The fact that what Dick is entertaining us about is reality and madness,time and death, sin and salvation -- this has escaped most readers and critics. Nobody notices; nobody notices that we have our own homegrown Borges, and have had him for 30 years
> -- Ursula K. Leguin, "Science Fiction as Prophesy" [-@leguin_science_1976]^[The original article from *The New Repulbic* vol. 175 is not readily available online, so this quote was retrieved from "Edmundo Paz Soldán and his Precursors: Borges, Dick, and the SF Canon" [@soldan_edmundo_2007]. ]

The fact that PKD presented his work as a reflexion on the nature of reality and mankind warrants greater academic attention, which this blog will hopefully contribute to^[On that matter, I blame the bias against science-fiction: the *serious* literary scene does not discuss it and reduces it to laser guns and aliens. (Do not take me wrong, I like laser guns and aliens as much as the next 30 years old man who's first memory of going to the cinema is seeing *Star Wars: The Phantom Menace* with their dad.) If I don't think that an apology of science-fiction is necessary, I might put in word my **strong** feelings on the matter in the future.]. 
But the main and central reason why I personally decided to write about Philip K. Dick is that I was, long ago, infected by his ideas. 

## The Dickian question

The question at the core of [Philip K. Dick](pkd_01.qmd)'s project is the same one that lead me to study physics at the graduate level, and the same one that still animates me in my literary studies to this day: "What is reality?"

> Reality is that which, when you stop believing in it, doesn't go away.
> -- Philip K. Dick, *I Hope I Shall Arrive Soon* [-@dick_hope_TODO]

Reality isn't something that is easy to understand; it seems that any one approach to try to grasp at it is a form of epistemic violence towards the universe itself, and a combination of approach inevariably leads to the need for incompatible points of view to exist simultaneously. Paul Valéry wrote "Nous ne raisonnons que par modèles" ["We only think through models", my translation], but systems are never complete, they do not hold to scrutiny like we hope something like a universe should/would. What if the (human) universe is, like language and mathematics, a system created by the network of affordances and perceptual horizons humans inherited from the laws of physics, language and culture? 

How does one take hold of the system of which they are a part of? This reformulation of the question can be applied to mathematics, physics and language alike: the pretension of objectivity fails systematically, is the unobserved universe worth creating? 

Studying the universe might lead to the same dead ends described by Gödel in his Incompleteness theorems: mathematical systems cannot justify themselves. According to the first incompletness theorem, there is no consistent set of axioms for mathematics that allows one to prove all truths about arithmetics. Even worse, the second incompletness theorem proves that no system can prove its own self-consistency. Beyond formal systems, Münchhausen's trilemna make a similar case for knowledge

Fries' Trilemna tries to address this limit by reframing the problem: things can be known dogmatically, through infinite regresses, or by basing oneself on perceptual experience. This answer seems to point to empiricism as a simple solution to the problem of epistemology, but perceptual experience is not something you can systematically trust, and for someone like Philip K. Dick who lived between multiple realities, perception can't be the answer: if most people cannot see the cage in which they stand, and the few that know t


Frank Herbert also touches on the Dickian question, although he comes at it from a spiritual (and less neurotic) avenue:

> She said the mystery of life isn’t a problem to solve, but a reality to experience. So I quoted the First Law of Mentat at her: "A process cannot be understood by stopping it. Understanding must move with the flow of the process, must join it and flow with it."
> -- Frank Herbert, *Dune* [-@herbert_dune_1965]

Dick does not see the mystery of life as a flow in which one can let themselves go, he knows enough to know the shape of the prison, and presents his view of breaking out in *Valis*:

> To fight the Empire is to be infected by its derangement ... Whoever defeats the Empire becomes the Empire; it proliferates like a virus ... thereby it becomes its enemies. 
> -- Philip K. Dick, *Valis* [-@dick_valis_TODO]