---
title: "Why Philip K. Dick?"
author: "Yann Audin"
date: "2025-01-21"
categories: ["Philip K. Dick Project", "Literature"]
tags: ["Philip K. Dick"]
format:
  html:
    toc: true
    number-sections: true
    code-fold: true
description: "A brief description of the post for SEO and previews."
draft: true # Set to false when ready to publish
---

> Is there anyone there
> Who understands me?
> Anyone at all?
> [...]
> I have to know what is real
> And what is illusion
> Oh, how does it feel
> Beyond this confusion?
> 
> -- "Monkeyland", The Chameleons UK (1983)

## The Dickian question

The question at the core of [Philip K. Dick](pkd_01)'s project is the same one that lead me to study physics at the graduate level, and the same one that still animates me in my literary studies to this day: "What is reality?"

> Reality is that which, when you stop believing in it, doesn't go away.
> -- Philip K. Dick, *I Hope I Shall Arrive Soon* [-@dick_hope_TODO]

Reality isn't something that is easy to understand; it seems that any approach to try to grasp at it is a form of violence towards the universe. How does one take hold of the system of which they are a part of? This reformulation of the question can be applied to mathematics and language, which brings us to a problem: these systems are not complete, they do not hold to scrutiny like we hope something like the universe would. What if the universe is, like language and mathematics, a system created by the network of affordances and perceptual horizons humans inherited from the laws of physics, language and culture? Studying the universe might lead to the same dead ends described by Gödel in his Incompleteness theorems; maybe the only solutions are infinite regression (nihilism), cyclical explanations (absurdism) or axiomatism (faith). Frank Herbert also touches on the Dickian question, although he comes at it from a spiritual (and less neurotic) avenue:

> She said the mystery of life isn’t a problem to solve, but a reality to experience. So I quoted the First Law of Mentat at her: "A process cannot be understood by stopping it. Understanding must move with the flow of the process, must join it and flow with it."
> -- Frank Herbert, *Dune* [-@herbert_dune_1965]

Dick does not see the mystery of life as a flow in which one can let themselves go, he knows enough to know the shape of the prison, and presents his view of breaking out in *Valis*:

> To fight the Empire is to be infected by its derangement ... Whoever defeats the Empire becomes the Empire; it proliferates like a virus ... thereby it becomes its enemies. 
> -- Philip K. Dick, *Valis* [-@dick_valis_TODO]

### No one is prophet in their own (time or) country

My views on Philip K. Dick are tainted by regret: on one hand, if he had been born at any other time or place, he might have been taken seriously; he might have been the philosopher his time as well as our time needed. On the other hand, if he had been born at any other time or place, he wouldn't be Philip K. Dick. His work was confined to science-fiction by material and cultural forces beyond his control -- he only manage to have one of his non-scifi novel published -- keeping his idea in stasis, away from serious criticism. 

> The fact that what Dick is entertaining us about is reality and madness,time and death, sin and salvation -- this has escaped most readers and critics. Nobody notices; nobody notices that we have our own homegrown Borges, and have had him for 30 years
> -- Ursula K. Leguin, "Science Fiction as Prophesy" [-@leguin_science_1976]^[The original article fro *The New Repulbic* vol. 175 is not readily available online, so this quote was retrieved from "Edmundo Paz Soldán and his Precursors: Borges, Dick, and the SF Canon" [@soldan_edmundo_2007]. ]



## Why you should read Philip K. Dick

To know Philip K. Dick's work is to recognize Dickianism everywhere. When the nature of reality is contested in contemporary media, one can usually draw a line to Dick, either directly -- *Bladerunner*, *The Adjustment Bureau*, *Total Recall*, *Philip K. Dick's Electric Dreams*, *Minority Report*, ... -- or indirectly -- *The Matrix*, *Donnie Darko*, *The Truman Show*, *Westworld*, ...

This is not to say that Philip K. Dick changed much of the culture around him. In many ways, he was more a slave to the pressure of his time than many other authors who set themselves outside of the world as an observer, and he did not become a literary recluse. Dick was first and foremost an American white man who grew up and lived in an era of extraordinary and frightening technological and cultural transformations, and who became the nexus for the overwhelming forces of his time. 